# Continuous integration and delivery of the main branch.

name: CI/CD

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  release:
    # Automatic release will run on a Github-hosted machine
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Read Current Version
      id: read_property
      uses: christian-draeger/read-properties@1.0.0
      with:
        path: 'VERSION'
        property: 'version'

    - name: Current Version
      run: echo ${{ steps.read_property.outputs.value }}

    - name: Generate Release Notes
      # Retrieves the commit message from the last commit in current branch (main)
      # and writes it to a file called release_notes.txt
      run: git log --format=%B -n 1 ${{ github.event.after }} > release_notes.txt

    - name: Github Bumpversion Action
      id: version-bump
      uses: jasonamyers/github-bumpversion-action@v1.0.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: "patch"

    - name: New Version
      run: echo ${{ steps.version-bump.outputs.new_ver }}

    - name: Push Changes To Master/Main
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tags: true

    - name: Create Github release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version-bump.outputs.new_ver }}
        release_name: 'genomeshader_${{ steps.version-bump.outputs.new_ver }}'
        body_path: "release_notes.txt"
        draft: false
        prerelease: false

    - name: Slack Failure Notification
      if: failure()
      uses: rtCamp/action-slack-notify@v2.0.2
      env:
        SLACK_MESSAGE: 'Failed to release version genomeshader_${{ steps.version-bump.outputs.new_ver }}'
        SLACK_COLOR: '#DF5A49'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_ICON: https://github.com/broadinstitute/genomeshader/blob/main/.github/workflows/dnabad.png?raw=true
        SLACK_USERNAME: genomeshader

    - name: Slack Success Notification
      if: success()
      uses: rtCamp/action-slack-notify@v2.0.2
      env:
        SLACK_MESSAGE: 'Successfully released version genomeshader_${{ steps.version-bump.outputs.new_ver }}'
        SLACK_COLOR: '#50D9C9'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_ICON: https://github.com/broadinstitute/genomeshader/blob/main/.github/workflows/dnagood.png?raw=true
        SLACK_USERNAME: genomeshader